// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pack2/BackMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Pack2/BackMessage.proto</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class BackMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for Pack2/BackMessage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BackMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdQYWNrMi9CYWNrTWVzc2FnZS5wcm90byIeCgtCYWNrTWVzc2FnZRIPCgdj",
          "b250ZW50GAEgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BackMessage), global::BackMessage.Parser, new[]{ "Content" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class BackMessage : pb::IMessage<BackMessage> {
  private static readonly pb::MessageParser<BackMessage> _parser = new pb::MessageParser<BackMessage>(() => new BackMessage());
  public static pb::MessageParser<BackMessage> Parser { get { return _parser; } }

  public static pbr::MessageDescriptor Descriptor {
    get { return global::BackMessageReflection.Descriptor.MessageTypes[0]; }
  }

  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  public BackMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  public BackMessage(BackMessage other) : this() {
    content_ = other.content_;
  }

  public BackMessage Clone() {
    return new BackMessage(this);
  }

  /// <summary>Field number for the "content" field.</summary>
  public const int ContentFieldNumber = 1;
  private string content_ = "";
  public string Content {
    get { return content_; }
    set {
      content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  public override bool Equals(object other) {
    return Equals(other as BackMessage);
  }

  public bool Equals(BackMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Content != other.Content) return false;
    return true;
  }

  public override int GetHashCode() {
    int hash = 1;
    if (Content.Length != 0) hash ^= Content.GetHashCode();
    return hash;
  }

  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  public void WriteTo(pb::CodedOutputStream output) {
    if (Content.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Content);
    }
  }

  public int CalculateSize() {
    int size = 0;
    if (Content.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
    }
    return size;
  }

  public void MergeFrom(BackMessage other) {
    if (other == null) {
      return;
    }
    if (other.Content.Length != 0) {
      Content = other.Content;
    }
  }

  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Content = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
