// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pack2/DefeatMessage.proto

public final class DefeatMessageOuterClass {
    private DefeatMessageOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface DefeatMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:DefeatMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .DefeatMessage.Type type = 1;</code>
         */
        int getTypeValue();

        /**
         * <code>optional .DefeatMessage.Type type = 1;</code>
         */
        DefeatMessage.Type getType();

        /**
         * <code>optional .CallMessage callMessage = 2;</code>
         */
        boolean hasCallMessage();

        /**
         * <code>optional .CallMessage callMessage = 2;</code>
         */
        CallMessageOuterClass.CallMessage getCallMessage();

        /**
         * <code>optional .CallMessage callMessage = 2;</code>
         */
        CallMessageOuterClass.CallMessageOrBuilder getCallMessageOrBuilder();

        /**
         * <code>optional .BackMessage backMessage = 3;</code>
         */
        boolean hasBackMessage();

        /**
         * <code>optional .BackMessage backMessage = 3;</code>
         */
        BackMessageOuterClass.BackMessage getBackMessage();

        /**
         * <code>optional .BackMessage backMessage = 3;</code>
         */
        BackMessageOuterClass.BackMessageOrBuilder getBackMessageOrBuilder();
    }

    /**
     * Protobuf type {@code DefeatMessage}
     */
    public static final class DefeatMessage extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:DefeatMessage)
            DefeatMessageOrBuilder {
        // Use DefeatMessage.newBuilder() to construct.
        private DefeatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private DefeatMessage() {
            type_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private DefeatMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();

                            type_ = rawValue;
                            break;
                        }
                        case 18: {
                            CallMessageOuterClass.CallMessage.Builder subBuilder = null;
                            if (callMessage_ != null) {
                                subBuilder = callMessage_.toBuilder();
                            }
                            callMessage_ = input.readMessage(CallMessageOuterClass.CallMessage.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(callMessage_);
                                callMessage_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 26: {
                            BackMessageOuterClass.BackMessage.Builder subBuilder = null;
                            if (backMessage_ != null) {
                                subBuilder = backMessage_.toBuilder();
                            }
                            backMessage_ = input.readMessage(BackMessageOuterClass.BackMessage.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(backMessage_);
                                backMessage_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DefeatMessageOuterClass.internal_static_DefeatMessage_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DefeatMessageOuterClass.internal_static_DefeatMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            DefeatMessage.class, Builder.class);
        }

        /**
         * Protobuf enum {@code DefeatMessage.Type}
         */
        public enum Type
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>CallMessage = 0;</code>
             */
            CallMessage(0),
            /**
             * <code>BackMessage = 1;</code>
             */
            BackMessage(1),
            UNRECOGNIZED(-1),;

            /**
             * <code>CallMessage = 0;</code>
             */
            public static final int CallMessage_VALUE = 0;
            /**
             * <code>BackMessage = 1;</code>
             */
            public static final int BackMessage_VALUE = 1;


            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @Deprecated
            public static Type valueOf(int value) {
                return forNumber(value);
            }

            public static Type forNumber(int value) {
                switch (value) {
                    case 0:
                        return CallMessage;
                    case 1:
                        return BackMessage;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
                return internalValueMap;
            }

            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Type> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                        public Type findValueByNumber(int number) {
                            return Type.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return DefeatMessage.getDescriptor().getEnumTypes().get(0);
            }

            private static final Type[] VALUES = values();

            public static Type valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private Type(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:DefeatMessage.Type)
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;

        /**
         * <code>optional .DefeatMessage.Type type = 1;</code>
         */
        public int getTypeValue() {
            return type_;
        }

        /**
         * <code>optional .DefeatMessage.Type type = 1;</code>
         */
        public Type getType() {
            Type result = Type.forNumber(type_);
            return result == null ? Type.UNRECOGNIZED : result;
        }

        public static final int CALLMESSAGE_FIELD_NUMBER = 2;
        private CallMessageOuterClass.CallMessage callMessage_;

        /**
         * <code>optional .CallMessage callMessage = 2;</code>
         */
        public boolean hasCallMessage() {
            return callMessage_ != null;
        }

        /**
         * <code>optional .CallMessage callMessage = 2;</code>
         */
        public CallMessageOuterClass.CallMessage getCallMessage() {
            return callMessage_ == null ? CallMessageOuterClass.CallMessage.getDefaultInstance() : callMessage_;
        }

        /**
         * <code>optional .CallMessage callMessage = 2;</code>
         */
        public CallMessageOuterClass.CallMessageOrBuilder getCallMessageOrBuilder() {
            return getCallMessage();
        }

        public static final int BACKMESSAGE_FIELD_NUMBER = 3;
        private BackMessageOuterClass.BackMessage backMessage_;

        /**
         * <code>optional .BackMessage backMessage = 3;</code>
         */
        public boolean hasBackMessage() {
            return backMessage_ != null;
        }

        /**
         * <code>optional .BackMessage backMessage = 3;</code>
         */
        public BackMessageOuterClass.BackMessage getBackMessage() {
            return backMessage_ == null ? BackMessageOuterClass.BackMessage.getDefaultInstance() : backMessage_;
        }

        /**
         * <code>optional .BackMessage backMessage = 3;</code>
         */
        public BackMessageOuterClass.BackMessageOrBuilder getBackMessageOrBuilder() {
            return getBackMessage();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (type_ != Type.CallMessage.getNumber()) {
                output.writeEnum(1, type_);
            }
            if (callMessage_ != null) {
                output.writeMessage(2, getCallMessage());
            }
            if (backMessage_ != null) {
                output.writeMessage(3, getBackMessage());
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (type_ != Type.CallMessage.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_);
            }
            if (callMessage_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getCallMessage());
            }
            if (backMessage_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getBackMessage());
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        public static DefeatMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DefeatMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DefeatMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DefeatMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DefeatMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static DefeatMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static DefeatMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static DefeatMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static DefeatMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static DefeatMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(DefeatMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code DefeatMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:DefeatMessage)
                DefeatMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DefeatMessageOuterClass.internal_static_DefeatMessage_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DefeatMessageOuterClass.internal_static_DefeatMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                DefeatMessage.class, Builder.class);
            }

            // Construct using DefeatMessageOuterClass.DefeatMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                type_ = 0;

                if (callMessageBuilder_ == null) {
                    callMessage_ = null;
                } else {
                    callMessage_ = null;
                    callMessageBuilder_ = null;
                }
                if (backMessageBuilder_ == null) {
                    backMessage_ = null;
                } else {
                    backMessage_ = null;
                    backMessageBuilder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return DefeatMessageOuterClass.internal_static_DefeatMessage_descriptor;
            }

            public DefeatMessage getDefaultInstanceForType() {
                return DefeatMessage.getDefaultInstance();
            }

            public DefeatMessage build() {
                DefeatMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public DefeatMessage buildPartial() {
                DefeatMessage result = new DefeatMessage(this);
                result.type_ = type_;
                if (callMessageBuilder_ == null) {
                    result.callMessage_ = callMessage_;
                } else {
                    result.callMessage_ = callMessageBuilder_.build();
                }
                if (backMessageBuilder_ == null) {
                    result.backMessage_ = backMessage_;
                } else {
                    result.backMessage_ = backMessageBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof DefeatMessage) {
                    return mergeFrom((DefeatMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(DefeatMessage other) {
                if (other == DefeatMessage.getDefaultInstance()) return this;
                if (other.type_ != 0) {
                    setTypeValue(other.getTypeValue());
                }
                if (other.hasCallMessage()) {
                    mergeCallMessage(other.getCallMessage());
                }
                if (other.hasBackMessage()) {
                    mergeBackMessage(other.getBackMessage());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                DefeatMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (DefeatMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int type_ = 0;

            /**
             * <code>optional .DefeatMessage.Type type = 1;</code>
             */
            public int getTypeValue() {
                return type_;
            }

            /**
             * <code>optional .DefeatMessage.Type type = 1;</code>
             */
            public Builder setTypeValue(int value) {
                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .DefeatMessage.Type type = 1;</code>
             */
            public Type getType() {
                Type result = Type.forNumber(type_);
                return result == null ? Type.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .DefeatMessage.Type type = 1;</code>
             */
            public Builder setType(Type value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .DefeatMessage.Type type = 1;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private CallMessageOuterClass.CallMessage callMessage_ = null;
            private com.google.protobuf.SingleFieldBuilder<
                    CallMessageOuterClass.CallMessage, CallMessageOuterClass.CallMessage.Builder, CallMessageOuterClass.CallMessageOrBuilder> callMessageBuilder_;

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            public boolean hasCallMessage() {
                return callMessageBuilder_ != null || callMessage_ != null;
            }

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            public CallMessageOuterClass.CallMessage getCallMessage() {
                if (callMessageBuilder_ == null) {
                    return callMessage_ == null ? CallMessageOuterClass.CallMessage.getDefaultInstance() : callMessage_;
                } else {
                    return callMessageBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            public Builder setCallMessage(CallMessageOuterClass.CallMessage value) {
                if (callMessageBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    callMessage_ = value;
                    onChanged();
                } else {
                    callMessageBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            public Builder setCallMessage(
                    CallMessageOuterClass.CallMessage.Builder builderForValue) {
                if (callMessageBuilder_ == null) {
                    callMessage_ = builderForValue.build();
                    onChanged();
                } else {
                    callMessageBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            public Builder mergeCallMessage(CallMessageOuterClass.CallMessage value) {
                if (callMessageBuilder_ == null) {
                    if (callMessage_ != null) {
                        callMessage_ =
                                CallMessageOuterClass.CallMessage.newBuilder(callMessage_).mergeFrom(value).buildPartial();
                    } else {
                        callMessage_ = value;
                    }
                    onChanged();
                } else {
                    callMessageBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            public Builder clearCallMessage() {
                if (callMessageBuilder_ == null) {
                    callMessage_ = null;
                    onChanged();
                } else {
                    callMessage_ = null;
                    callMessageBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            public CallMessageOuterClass.CallMessage.Builder getCallMessageBuilder() {

                onChanged();
                return getCallMessageFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            public CallMessageOuterClass.CallMessageOrBuilder getCallMessageOrBuilder() {
                if (callMessageBuilder_ != null) {
                    return callMessageBuilder_.getMessageOrBuilder();
                } else {
                    return callMessage_ == null ?
                            CallMessageOuterClass.CallMessage.getDefaultInstance() : callMessage_;
                }
            }

            /**
             * <code>optional .CallMessage callMessage = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    CallMessageOuterClass.CallMessage, CallMessageOuterClass.CallMessage.Builder, CallMessageOuterClass.CallMessageOrBuilder>
            getCallMessageFieldBuilder() {
                if (callMessageBuilder_ == null) {
                    callMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            CallMessageOuterClass.CallMessage, CallMessageOuterClass.CallMessage.Builder, CallMessageOuterClass.CallMessageOrBuilder>(
                            getCallMessage(),
                            getParentForChildren(),
                            isClean());
                    callMessage_ = null;
                }
                return callMessageBuilder_;
            }

            private BackMessageOuterClass.BackMessage backMessage_ = null;
            private com.google.protobuf.SingleFieldBuilder<
                    BackMessageOuterClass.BackMessage, BackMessageOuterClass.BackMessage.Builder, BackMessageOuterClass.BackMessageOrBuilder> backMessageBuilder_;

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            public boolean hasBackMessage() {
                return backMessageBuilder_ != null || backMessage_ != null;
            }

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            public BackMessageOuterClass.BackMessage getBackMessage() {
                if (backMessageBuilder_ == null) {
                    return backMessage_ == null ? BackMessageOuterClass.BackMessage.getDefaultInstance() : backMessage_;
                } else {
                    return backMessageBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            public Builder setBackMessage(BackMessageOuterClass.BackMessage value) {
                if (backMessageBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    backMessage_ = value;
                    onChanged();
                } else {
                    backMessageBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            public Builder setBackMessage(
                    BackMessageOuterClass.BackMessage.Builder builderForValue) {
                if (backMessageBuilder_ == null) {
                    backMessage_ = builderForValue.build();
                    onChanged();
                } else {
                    backMessageBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            public Builder mergeBackMessage(BackMessageOuterClass.BackMessage value) {
                if (backMessageBuilder_ == null) {
                    if (backMessage_ != null) {
                        backMessage_ =
                                BackMessageOuterClass.BackMessage.newBuilder(backMessage_).mergeFrom(value).buildPartial();
                    } else {
                        backMessage_ = value;
                    }
                    onChanged();
                } else {
                    backMessageBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            public Builder clearBackMessage() {
                if (backMessageBuilder_ == null) {
                    backMessage_ = null;
                    onChanged();
                } else {
                    backMessage_ = null;
                    backMessageBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            public BackMessageOuterClass.BackMessage.Builder getBackMessageBuilder() {

                onChanged();
                return getBackMessageFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            public BackMessageOuterClass.BackMessageOrBuilder getBackMessageOrBuilder() {
                if (backMessageBuilder_ != null) {
                    return backMessageBuilder_.getMessageOrBuilder();
                } else {
                    return backMessage_ == null ?
                            BackMessageOuterClass.BackMessage.getDefaultInstance() : backMessage_;
                }
            }

            /**
             * <code>optional .BackMessage backMessage = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    BackMessageOuterClass.BackMessage, BackMessageOuterClass.BackMessage.Builder, BackMessageOuterClass.BackMessageOrBuilder>
            getBackMessageFieldBuilder() {
                if (backMessageBuilder_ == null) {
                    backMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            BackMessageOuterClass.BackMessage, BackMessageOuterClass.BackMessage.Builder, BackMessageOuterClass.BackMessageOrBuilder>(
                            getBackMessage(),
                            getParentForChildren(),
                            isClean());
                    backMessage_ = null;
                }
                return backMessageBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:DefeatMessage)
        }

        // @@protoc_insertion_point(class_scope:DefeatMessage)
        private static final DefeatMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new DefeatMessage();
        }

        public static DefeatMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<DefeatMessage>
                PARSER = new com.google.protobuf.AbstractParser<DefeatMessage>() {
            public DefeatMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DefeatMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DefeatMessage> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<DefeatMessage> getParserForType() {
            return PARSER;
        }

        public DefeatMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_DefeatMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_DefeatMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_DefeatMessage_descriptor,
            new String[]{"Type", "CallMessage", "BackMessage",});

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\031Pack2/DefeatMessage.proto\032\027Pack2/BackM" +
                        "essage.proto\032\027Pack2/CallMessage.proto\"\242\001" +
                        "\n\rDefeatMessage\022!\n\004type\030\001 \001(\0162\023.DefeatMe" +
                        "ssage.Type\022!\n\013callMessage\030\002 \001(\0132\014.CallMe" +
                        "ssage\022!\n\013backMessage\030\003 \001(\0132\014.BackMessage" +
                        "\"(\n\004Type\022\017\n\013CallMessage\020\000\022\017\n\013BackMessage" +
                        "\020\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };


        com.google.protobuf.Descriptors.FileDescriptor[] dependences = new com.google.protobuf.Descriptors.FileDescriptor[]
                {
                        BackMessageOuterClass.getDescriptor(),
                        CallMessageOuterClass.getDescriptor()
                };


        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                dependences,
                assigner);


        BackMessageOuterClass.getDescriptor();
        CallMessageOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
